export const Users = [
	{
		id: 1,
		profilePicture: "assets/Profile//1.jpg",
		username: "Fanny Rodriguez",
	},
	{
		id: 2,
		profilePicture: "assets/Profile//2.jpg",
		username: "Vicki Smith",
	},
	{
		id: 3,
		profilePicture: "assets/Profile//3.jpg",
		username: "Micah Durden",
	},
	{
		id: 4,
		profilePicture: "assets/Profile//4.jpg",
		username: "Khloe Buttons",
	},
	{
		id: 5,
		profilePicture: "assets/Profile//5.jpg",
		username: "Gary Brown",
	},
	{
		id: 6,
		profilePicture: "assets/Profile//6.jpg",
		username: "Jimmy Butler",
	},
	{
		id: 7,
		profilePicture: "assets/Profile//7.jpg",
		username: "Jason Michael Thomas",
	},
	{
		id: 8,
		profilePicture: "assets/Profile//8.jpg",
		username: "Osaramen Bennet",
	},
	{
		id: 9,
		profilePicture: "assets/Profile//9.jpg",
		username: "Nev Varnerbux",
	},
	{
		id: 10,
		profilePicture: "assets/Profile/10.jpg",
		username: "Jim Cauldwell",
	},
	{
		id: 11,
		profilePicture:
			"https://pbs.twimg.com/profile_images/1432019279180812291/hcQfssM5_400x400.jpg",
		username: "Joseph Joslin",
	},
];

export const Posts = [
	{
		id: 1,
		desc: "Fresh berries and protein I'm ready for summer!.",
		photo: "assets/Posts/1.jpg",
		date: "5 mins ago",
		userId: 1,
		likes: Math.floor(Math.random() * 100),
		loves: Math.floor(Math.random() * 100),
		funny: Math.floor(Math.random() * 100),
		comment: Math.floor(Math.random() * 100),
	},
	{
		id: 2,
		photo: "assets/Posts/2.jpg",
		date: "15 mins ago",
		userId: 2,
		likes: Math.floor(Math.random() * 100),
		loves: Math.floor(Math.random() * 100),
		funny: Math.floor(Math.random() * 100),
		comment: Math.floor(Math.random() * 100),
	},
	{
		id: 3,
		desc: "Every moment is a fresh beginning.",
		photo: "assets/Posts/3.jpg",
		date: "1 hour ago",
		userId: 3,
		likes: Math.floor(Math.random() * 100),
		loves: Math.floor(Math.random() * 100),
		funny: Math.floor(Math.random() * 100),
		comment: Math.floor(Math.random() * 100),
	},
	{
		id: 4,
		photo: "assets/Posts/4.jpg",
		date: "4 hours ago",
		userId: 4,
		likes: Math.floor(Math.random() * 100),
		loves: Math.floor(Math.random() * 100),
		funny: Math.floor(Math.random() * 100),
		comment: Math.floor(Math.random() * 100),
	},
	{
		id: 5,
		photo: "assets/Posts/5.jpg",
		date: "5 hours ago",
		userId: 5,
		likes: Math.floor(Math.random() * 100),
		loves: Math.floor(Math.random() * 100),
		funny: Math.floor(Math.random() * 100),
		comment: Math.floor(Math.random() * 100),
	},
	{
		id: 6,
		photo: "assets/Posts/6.jpg",
		date: "1 day ago",
		userId: 6,
		likes: Math.floor(Math.random() * 100),
		loves: Math.floor(Math.random() * 100),
		funny: Math.floor(Math.random() * 100),
		comment: Math.floor(Math.random() * 100),
	},
	{
		id: 7,
		desc: "Never regret anything that made you smile.",
		photo: "assets/Posts/7.jpg",
		date: "2 days ago",
		userId: 7,
		likes: Math.floor(Math.random() * 100),
		loves: Math.floor(Math.random() * 100),
		funny: Math.floor(Math.random() * 100),
		comment: Math.floor(Math.random() * 100),
	},
	{
		id: 8,
		photo: "assets/Posts/8.jpg",
		date: "3 days ago",
		userId: 8,
		likes: Math.floor(Math.random() * 100),
		loves: Math.floor(Math.random() * 100),
		funny: Math.floor(Math.random() * 100),
		comment: Math.floor(Math.random() * 100),
	},
	{
		id: 9,
		desc: "Change the world by being yourself.",
		photo: "assets/Posts/9.jpg",
		date: "5 days ago",
		userId: 9,
		likes: Math.floor(Math.random() * 100),
		loves: Math.floor(Math.random() * 100),
		funny: Math.floor(Math.random() * 100),
		comment: Math.floor(Math.random() * 100),
	},
	{
		id: 10,
		photo: "assets/Posts/10.jpg",
		date: "1 week ago",
		userId: 10,
		loves: Math.floor(Math.random() * 100),
		funny: Math.floor(Math.random() * 100),
		likes: Math.floor(Math.random() * 100),
		comment: Math.floor(Math.random() * 100),
	},
	{
		id: 11,
		desc: "Bees are changing the game",
		photo:
			"https://cdn.britannica.com/s:800x450,c:crop/78/192578-138-DC7C6A32/conservation-efforts-bee-populations-plant-animal-species.jpg",
		date: "1 week ago",
		userId: 11,
		loves: Math.floor(Math.random() * 100),
		funny: Math.floor(Math.random() * 100),
		likes: Math.floor(Math.random() * 100),
		comment: Math.floor(Math.random() * 100),
	},
	{
		id: 12,
		desc: "If at first you don't succeed, you should probably quit. I mean did you really want to do this anyway?",
		photo: "",
		date: "1 week ago",
		userId: 11,
		loves: Math.floor(Math.random() * 100),
		funny: Math.floor(Math.random() * 100),
		likes: Math.floor(Math.random() * 100),
		comment: Math.floor(Math.random() * 100),
	},
];
