export const Users = [
	{
		id: 1,
		profilePicture: "Profile/1.jpg",
		username: "Fanny Rodriguez",
	},
	{
		id: 2,
		profilePicture: "Profile/2.jpg",
		username: "Vicki Smith",
	},
	{
		id: 3,
		profilePicture: "Profile/3.jpg",
		username: "Micah Durden",
	},
	{
		id: 4,
		profilePicture: "Profile/4.jpg",
		username: "Khloe Buttons",
	},
	{
		id: 5,
		profilePicture: "Profile/5.jpg",
		username: "Gary Brown",
	},
	{
		id: 6,
		profilePicture: "Profile/6.jpg",
		username: "Jimmy Butler",
	},
	{
		id: 7,
		profilePicture: "Profile/7.jpg",
		username: "Jason Michael Thomas",
	},
	{
		id: 8,
		profilePicture: "Profile/8.jpg",
		username: "Osaramen Bennet",
	},
	{
		id: 9,
		profilePicture: "Profile/9.jpg",
		username: "Nev Varnerbux",
	},
	{
		id: 10,
		profilePicture: "Profile/10.jpg",
		username: "Jim Cauldwell",
	},
];

export const Posts = [
	{
		id: 1,
		desc: "Fresh berries and protein I'm ready for summer!.",
		photo: "Posts/1.jpg",
		date: "5 mins ago",
		userId: 1,
		likes: Math.floor(Math.random() * 100),
		loves: Math.floor(Math.random() * 100),
		funny: Math.floor(Math.random() * 100),
		comment: Math.floor(Math.random() * 100),
	},
	{
		id: 2,
		photo: "Posts/2.jpg",
		date: "15 mins ago",
		userId: 2,
		likes: Math.floor(Math.random() * 100),
		loves: Math.floor(Math.random() * 100),
		funny: Math.floor(Math.random() * 100),
		comment: Math.floor(Math.random() * 100),
	},
	{
		id: 3,
		desc: "Every moment is a fresh beginning.",
		photo: "Posts/3.jpg",
		date: "1 hour ago",
		userId: 3,
		likes: Math.floor(Math.random() * 100),
		loves: Math.floor(Math.random() * 100),
		funny: Math.floor(Math.random() * 100),
		comment: Math.floor(Math.random() * 100),
	},
	{
		id: 4,
		photo: "Posts/4.jpg",
		date: "4 hours ago",
		userId: 4,
		likes: Math.floor(Math.random() * 100),
		loves: Math.floor(Math.random() * 100),
		funny: Math.floor(Math.random() * 100),
		comment: Math.floor(Math.random() * 100),
	},
	{
		id: 5,
		photo: "Posts/5.jpg",
		date: "5 hours ago",
		userId: 5,
		likes: Math.floor(Math.random() * 100),
		loves: Math.floor(Math.random() * 100),
		funny: Math.floor(Math.random() * 100),
		comment: Math.floor(Math.random() * 100),
	},
	{
		id: 6,
		photo: "Posts/6.jpg",
		date: "1 day ago",
		userId: 6,
		likes: Math.floor(Math.random() * 100),
		loves: Math.floor(Math.random() * 100),
		funny: Math.floor(Math.random() * 100),
		comment: Math.floor(Math.random() * 100),
	},
	{
		id: 7,
		desc: "Never regret anything that made you smile.",
		photo: "Posts/7.jpg",
		date: "2 days ago",
		userId: 7,
		likes: Math.floor(Math.random() * 100),
		loves: Math.floor(Math.random() * 100),
		funny: Math.floor(Math.random() * 100),
		comment: Math.floor(Math.random() * 100),
	},
	{
		id: 8,
		photo: "Posts/8.jpg",
		date: "3 days ago",
		userId: 8,
		likes: Math.floor(Math.random() * 100),
		loves: Math.floor(Math.random() * 100),
		funny: Math.floor(Math.random() * 100),
		comment: Math.floor(Math.random() * 100),
	},
	{
		id: 9,
		desc: "Change the world by being yourself.",
		photo: "Posts/9.jpg",
		date: "5 days ago",
		userId: 9,
		likes: Math.floor(Math.random() * 100),
		loves: Math.floor(Math.random() * 100),
		funny: Math.floor(Math.random() * 100),
		comment: Math.floor(Math.random() * 100),
	},
	{
		id: 10,
		photo: "Posts/10.jpg",
		date: "1 week ago",
		userId: 10,
		loves: Math.floor(Math.random() * 100),
		funny: Math.floor(Math.random() * 100),
		likes: Math.floor(Math.random() * 100),
		comment: Math.floor(Math.random() * 100),
	},
];
